### PR TITLE
Refactoring info dialog

### PR DESCRIPTION
**Pull request by hrishikeshpaul**
- [x] RUI
- [x] EUI

### CODE REVIEW

**Review by bherr2 — CHANGES_REQUESTED** [review]
Styling is not being applied to the expansion panels on the EUI like it is on the RUI. Please make sure they both follow the same styling/sizing.
EUI: https://60412597db5df5073c4b5c9b--hubmap-ccf-ui.netlify.app/
RUI: https://hubmap-ccf-ui.netlify.app/rui/

**Comment by hrishikeshpaul** [comment]
@bherr2 yeah I'm working on that. Can't figure out why the styles arent being applied

**Comment by bherr2** [comment]
> @bherr2 yeah I'm working on that. Can't figure out why the styles arent being applied

I'm thinking its got to do with styles and being in a separate library (ccf-shared), but I'm not sure. @axdanbol can you have a peek?

**Comment by hrishikeshpaul** [comment]
@bherr2 It works on the RUI. So my guess would be that something in the EUI is causing the expansion panels to disappear

**Comment by bherr2** [comment]
> @bherr2 It works on the RUI. So my guess would be that something in the EUI is causing the expansion panels to disappear

Or that expansion panel styles are included in the RUI but not the EUI. I don't recall there being any expansion panels in the previous version of the EUI.

**Comment by hrishikeshpaul** [comment]
I thought the styles are included with the component and when you import angular material. Let me investigate what is happening

**Comment by axdanbol** [comment]
You need to add `@include mat-expansion-panel-theme($theme);` to _theming.scss

**Review by bherr2 — APPROVED** [review]

**Pull request merged**
