### PR TITLE
Pbi 278 anatomical structure tags

### PR DESCRIPTION
**Pull request by axdanbol**

### CODE REVIEW

**Review by bherr2 — COMMENTED** [review]
Styling looks pretty close to the spec, but the thing isn't functional. Autocomplete shows two possible things to select, but it never adds to the list, doesn't show up on the debug screen in the middle. You should also be able to add freetext stuff from the 'search' bar. So I should be able to type 'foobar' and press plus and it still show in the list. I also can't tell if the scrollbar will appear after 3 lines of tags since no tags can be added/removed.

Were you intending on adding in these features after merging the look/feel to develop?

**Comment by axdanbol** [comment]
I'm planning to hook it up to the state during the weekend

**Comment by bherr2** [comment]
> I'm planning to hook it up to the state during the weekend

Ok, should I merge this and you setup another PR then? It might be good so I can hand the progress off to lecross to review so we can incorporate his feedback into the next sprint.

**Comment by axdanbol** [comment]
Yes please

**Review by bherr2 — APPROVED** [review]

**Pull request merged**
