### PR TITLE
Refactoring info dialog; add spatial-search readme

### PR DESCRIPTION
**Pull request by edlu77**
#842

### CODE REVIEW

**Comment by bherr2** [comment]
How can we see/verify the spatial search dialog content?

**Comment by edlu77** [comment]
> How can we see/verify the spatial search dialog content?

I would have to add another info button, is that all right?

**Comment by bherr2** [comment]
A screenshot will do actually

**Comment by bherr2** [comment]
Also, tests are failing

**Comment by edlu77** [comment]
> 

image

**Comment by edlu77** [comment]
Updated info screen

image

**Review by axdanbol — APPROVED** [review]
Looks good!

**Pull request merged**
