### PR TITLE
Show confirmation dialog when leaving the site

### PR DESCRIPTION
**Pull request by axdanbol**
Feature can be enabled/disabled either through the environment file or setting `skipUnsavedChangesConfirmation` on `window`

### CODE REVIEW

**Comment by bherr2** [comment]
* Need to also be able to set the pref in the RUI web-component
* Need to improve logic so that we aren't telling them to save if they've not actually changed anything. I know this bit is tough with the state the way it is. Were you planning on adding it as a follow up?

**Comment by axdanbol** [comment]
> * Need to also be able to set the pref in the RUI web-component
> * Need to improve logic so that we aren't telling them to save if they've not actually changed anything. I know this bit is tough with the state the way it is. Were you planning on adding it as a follow up?

I'll start with doing the first point.
For the second point I need to know what is considered a change. This is what I am current thinking should be tracked:
- AS tags
- Model
  - Except: viewType, viewSide, showPrevious

Any thoughts?

**Comment by bherr2** [comment]
Yeah, I just looked through our state and I agree with your assessment of which values to monitor to determine if there is an unsaved change.

**Comment by bherr2** [comment]
This doesn't cover the case when they create a rui location, save it, and then make more changes. They should be asked then as well.

**Review by bherr2 — APPROVED** [review]

**Pull request merged**
