### PR TITLE
WIP: Updated styles to match spec

### PR DESCRIPTION
**Pull request by hrishikeshpaul**

### CODE REVIEW

**Comment by bherr2** [comment]
@hrishikeshpaul why did you close this?

**Comment by hrishikeshpaul** [comment]
@bherr2 Because I'll need to open a new one. I forgot to change the target branch :(

**Comment by bherr2** [comment]
You can edit that at the top of the PR

**Comment by hrishikeshpaul** [comment]
oh, I didn't know that. Let me try it out

**Review by bherr2 — APPROVED** [review]

**Pull request merged**
